name: PSX Stock Tracker

on:
  schedule:
    # Monday-Thursday
    # 04:30-11:00 UTC = 09:30-16:00 PKT
    - cron: "*/5 4-10 * * 1-4"

    # Friday
    # 04:00-07:00 UTC = 09:00-12:00 PKT
    # 09:00-12:00 UTC = 14:00-17:00 PKT
    - cron: "*/5 4-6 * * 5"
    - cron: "*/5 9-11 * * 5"

  workflow_dispatch:

jobs:
  update-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run PSX tracker
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          MANUAL_RUN: ${{ github.event_name == 'workflow_dispatch' && '1' || '0' }}
        run: |
          python psx.py
