name: PSX Stock Tracker

on:
  schedule:
    # Monday - Thursday (09:07 to 15:57 PKT)
    - cron: "7-57/10 4-10 * * 1-4"

    # Monday - Thursday final run (16:07 PKT)
    - cron: "7 11 * * 1-4"

    # Friday morning (09:07 to 11:57 PKT)
    - cron: "7-57/10 4-6 * * 5"

    # Friday afternoon (14:07 to 15:57 PKT)
    - cron: "7-57/10 9-10 * * 5"

    # Friday final run (16:07 PKT)
    - cron: "7 11 * * 5"

  workflow_dispatch:

permissions:
  contents: read

jobs:
  update-stocks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PSX Tracker
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          MANUAL_RUN: ${{ github.event_name == 'workflow_dispatch' && '1' || '0' }}
        run: python psx.py